name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add steps to build your application
      # For example, if you're using Node.js:
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build  # Adjust according to your build process

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        uses: aws-actions/aws-cli@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your AWS region

      - name: Deploy to EC2 using CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name MyApp \
            --deployment-group-name MyDeploymentGroup \
            --s3-location bucket=your-bucket,key=your-app.zip,bundleType=zip
        env:
          AWS_DEFAULT_REGION: ap-south-1  # Change to your AWS region

