version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install   # Install dependencies
  build:
    commands:
      - npm run build # Or any other build command suitable for your application
artifacts:
  files:
    - '**/*' # Include all files in the artifact
